modLoader="javafml"

loaderVersion="${loader_version_range}"

license="MIT"

[[mods]]

modId="pesky_scalies"

version="1.0.0-1.21.1"

displayName="Pesky Scalies"

logoFile= "pesky_scalies.png"

description='''
Adds fictional reptiles and other animals to minecraft
'''

[[dependencies.pesky_scalies]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pesky_scalies]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
